import Head from "next/head";
import Hero from "../components/Hero";
import Loader from "../components/Loader";
import Navbar from "../components/Navbar";
import { useEffect, useState } from "react";
import Partner from "../components/Partner";
import ServiceItem from "../components/ServiceItem";

export default function Home() {
  const [loading, setLoading] = useState();

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  }, []);
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-ClashDisplay-Regular">
        {loading ? (
          <div>
            <Loader />
          </div>
        ) : (
          <div>
            <Navbar />
            <Hero />
            <Partner />
            <ServiceItem />
          </div>
        )}
      </div>
    </div>
  );
}
